'use client';
import { Cloud, Droplets, Eye } from 'lucide-react';
import { timeLabel } from '@/lib/sky';
type Hourly = {time:number[];[key:string]:(number|null)[]};
const valid=(n:unknown):n is number=>typeof n==='number'&&Number.isFinite(n);
export default function AtmosphereDetails({hourly,date,timezone,loading}:{hourly?:Hourly;date:Date;timezone:string;loading:boolean}){
 const hour=Math.floor(+date/3600000)*3600,index=hourly?.time.indexOf(hour)??-1;
 const get=(key:string)=>index>=0?hourly?.[key]?.[index]:undefined;
 const temp=get('temperature_2m'),dew=get('dew_point_2m'),visibility=get('visibility');
 const margin=valid(temp)&&valid(dew)?temp-dew:null;
 return <section className="panel atmosphere-panel" aria-labelledby="atmosphere-title"><div className="section-label"><span id="atmosphere-title">CLOUDS, HAZE & DEW</span><span className="muted">{timeLabel(new Date(hour*1000),timezone)} · {timezone}</span></div>{loading?<p className="muted" role="status">Loading atmospheric conditions…</p>:index<0?<p className="muted">No atmospheric forecast for this hour. Select a time within the forecast window.</p>:<><div className="atmosphere-grid"><div><h3><Cloud size={18}/>Cloud layers</h3><div className="cloud-layers">{[['High clouds','cloud_cover_high','Above 8 km'],['Middle clouds','cloud_cover_mid','3–8 km'],['Low clouds','cloud_cover_low','Below 3 km, including fog']].map(([name,key,range])=>{const n=get(key),available=valid(n)&&n>=0&&n<=100;return <div key={key}><div><span>{name}</span><strong>{available?`${Math.round(n)}%`:'Unavailable'}</strong></div><div className="cloud-layer-bar" aria-hidden="true"><span style={{width:available?`${n}%`:'0%'}}/></div><small>{range}</small></div>})}</div><p className="footnote">Layers can overlap; their percentages do not add up to total cloud cover.</p></div><div><h3><Droplets size={18}/>Dew on optics</h3><dl className="atmosphere-facts"><div><dt>Air temperature</dt><dd>{valid(temp)?`${temp.toFixed(1)} °C`:'Unavailable'}</dd></div><div><dt>Dew point</dt><dd>{valid(dew)?`${dew.toFixed(1)} °C`:'Unavailable'}</dd></div><div><dt>Temperature above dew point</dt><dd>{margin!==null?`${margin.toFixed(1)} °C`:'Unavailable'}</dd></div></dl><p className="atmosphere-guidance">{margin===null?'Dew guidance is unavailable without both temperatures.':margin<=2?'Air temperature is close to the dew point. Watch your optics for condensation.':'Air temperature is above the dew point, but exposed optics can cool faster than the air.'}</p><p className="footnote">The 2 °C marker is a planning rule of thumb, not a dew prediction. Actual lens temperature is not measured.</p></div><div><h3><Eye size={18}/>Near-surface visibility</h3><strong className="visibility-value">{valid(visibility)&&visibility>=0?`${(visibility/1000).toFixed(1)} km`:'Unavailable'}</strong><p className="atmosphere-guidance">Horizontal visibility can be reduced by fog, low cloud, humidity and aerosols.</p><p className="footnote">This is not an astronomical transparency or seeing measurement. Good ground visibility does not guarantee a clear view through the full atmosphere.</p></div></div><p className="footnote">Forecast variables and cloud-layer definitions: <a href="https://open-meteo.com/en/docs" target="_blank" rel="noreferrer">Open-Meteo documentation ↗</a>. Select an hour above to update this panel.</p></>}</section>;
}
