'use client';
import {framingGuide,type TargetExtent} from '@/lib/framing-guide';
export default function FramingGuide({width,height,cols,rows,overlap,rotation,target}:{width:number;height:number;cols:number;rows:number;overlap:number;rotation:number;target?:TargetExtent&{id:string}}){
 const guide=framingGuide(width,height,cols,rows,overlap,rotation,target);if(!guide)return null;
 const scale=Math.min(430/(guide.extentX*2),260/(guide.extentY*2)),x=(value:number)=>250+value*scale,y=(value:number)=>165-value*scale;
 return <figure className="framing-guide" aria-label="Target and mosaic framing comparison"><div className="section-label"><span>FRAMING GUIDE</span><span>N ↑ · E →</span></div><svg viewBox="0 0 500 330" role="img" aria-label={`${cols} by ${rows} camera grid rotated ${rotation} degrees east of north${guide.object?`, with ${target!.id} catalogue ${guide.object.uncertain?'major-axis bounding circle':'ellipse'}`:''}`}>
 <line x1="250" x2="250" y1="20" y2="310" stroke="#49616a" strokeDasharray="3 6"/><line x1="20" x2="480" y1="165" y2="165" stroke="#49616a" strokeDasharray="3 6"/>
 {guide.panels.map(panel=><g key={panel.number}><polygon points={panel.corners.map(point=>`${x(point.x)},${y(point.y)}`).join(' ')} fill="#c1df93" fillOpacity=".06" stroke="#c1df93" strokeWidth="1.5"/><text x={x(panel.centre.x)} y={y(panel.centre.y)} textAnchor="middle" dominantBaseline="middle" fontSize="16" fill="#e9f0f0">{panel.number}</text></g>)}
 {guide.object&&<ellipse cx="250" cy="165" rx={guide.object.rx*scale} ry={guide.object.ry*scale} transform={`rotate(${guide.object.angle} 250 165)`} fill="#efba82" fillOpacity=".12" stroke="#efba82" strokeWidth="2" strokeDasharray={guide.object.uncertain?'5 4':undefined}/>}
 <circle cx="250" cy="165" r="3" fill="#efba82"/>
 </svg><figcaption><p><strong>{cols*rows} panels</strong> · {overlap}% overlap · {rotation}° rotation</p><p>Single frame: {width.toFixed(2)}° × {height.toFixed(2)}° · Grid span: {guide.spanWidth.toFixed(2)}° × {guide.spanHeight.toFixed(2)}°</p>{guide.object?<><p className="framing-fit" role="status">{target!.id}: {guide.object.fitsFrame?'catalogue outline fits a centred single frame':guide.object.fitsMosaic?'catalogue outline fits the schematic mosaic bounds':'catalogue outline extends beyond this mosaic'}.</p><p className="footnote">Orange: {guide.object.uncertain?'major-axis bounding circle; a minor axis or position angle is unavailable':'catalogue extent and major-axis position angle'}. Green: camera panels. North is up, east is right. Shapes compare angular scale in the mosaic’s tangent plane; they are not a sky image, surface-brightness map or guaranteed object boundary. Panel orientations away from the centre are approximate.</p></>:<p className="footnote">Choose a catalogue object with a listed angular size to compare its extent. Green outlines show the camera grid, north up and east right. Small-field schematic, not a sky image.</p>}</figcaption></figure>;
}
