'use client';
import { useMemo, useState } from 'react';
import { ArrowUpRight, Moon } from 'lucide-react';
import { A, Place, bodyPosition } from '@/lib/sky';

export default function LunarEclipses({date,place,onDate}:{date:Date;place:Place;onDate:(date:Date)=>void}) {
 const events=useMemo(()=>{let event=A.SearchLunarEclipse(new Date(date.getTime()-86400000));if(event.peak.date.getTime()<date.getTime()-60000)event=A.NextLunarEclipse(event.peak);return Array.from({length:3},()=>{const item=event;event=A.NextLunarEclipse(item.peak);return item})},[date]);
 const [index,setIndex]=useState(0);
 const eclipse=events[index]||events[0];
 const contacts=[{label:'Penumbral begins',minutes:-eclipse.sd_penum},...(eclipse.sd_partial>0?[{label:'Partial begins',minutes:-eclipse.sd_partial}]:[]),...(eclipse.sd_total>0?[{label:'Totality begins',minutes:-eclipse.sd_total}]:[]),{label:'Greatest eclipse',minutes:0},...(eclipse.sd_total>0?[{label:'Totality ends',minutes:eclipse.sd_total}]:[]),...(eclipse.sd_partial>0?[{label:'Partial ends',minutes:eclipse.sd_partial}]:[]),{label:'Penumbral ends',minutes:eclipse.sd_penum}].map(c=>{const time=new Date(eclipse.peak.date.getTime()+c.minutes*60000);return {...c,time,altitude:bodyPosition(A.Body.Moon,time,place).altitude}});
 const format=(d:Date)=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:place.timezone||'UTC'}).format(d);
 return <section className="panel eclipse-panel" aria-labelledby="eclipse-heading"><div className="section-label"><span id="eclipse-heading">UPCOMING LUNAR ECLIPSES</span><Moon size={18}/></div><p className="muted">The next three events from your observing time (including a peak within the current minute). Select one to check its phases at {place.name}.</p><div className="eclipse-picker">{events.map((e,i)=><button className={eclipse===e?'active':''} key={e.peak.date.toISOString()} aria-pressed={eclipse===e} onClick={()=>setIndex(i)}><strong>{e.kind} eclipse</strong><span>{format(e.peak.date)}</span></button>)}</div><div className="eclipse-summary"><div><h3>{eclipse.kind} lunar eclipse</h3><p className="muted">{Math.round(eclipse.obscuration*100)}% of the Moon’s disc in Earth’s umbra at greatest eclipse.{eclipse.kind===A.EclipseKind.Penumbral?' Penumbral shading is subtle and can be difficult to notice.':''}</p></div><button className="text-button" onClick={()=>{setIndex(0);onDate(eclipse.peak.date)}}>Set observing time to peak <ArrowUpRight size={16}/></button></div><p className="eclipse-zone">Contact times in {place.timezone||'UTC'} · Moon altitude at {place.name}</p><ol className="eclipse-contacts">{contacts.map(c=><li key={c.label}><span>{c.label}</span><time dateTime={c.time.toISOString()}>{format(c.time)}</time><strong className={c.altitude>0?'above':'below'}>{c.altitude.toFixed(1)}° · {c.altitude>0?'Above':'Below'} horizon</strong></li>)}</ol><p className="footnote">These are global eclipse contact times, with local Moon altitude calculated for each contact. Above the horizon does not guarantee a clear view: weather, terrain and buildings are not included. The globe above shows ordinary phase lighting and does not simulate Earth’s shadow.</p></section>;
}
