'use client';
import {lazy,useMemo,useState} from 'react';
import {Moon,ArrowUpRight} from 'lucide-react';
import LunarEclipses from '@/components/lunar-eclipses';
import DeferredView from '@/components/deferred-view';
import {landmarks} from '@/lib/lunar-landmarks';
const MoonGlobe=lazy(()=>import('@/components/moon-globe'));
import {Switch} from '@/components/ui/switch';
import {A,Place,moonInfo,timeLabel} from '@/lib/sky';
export default function MoonExplorer({date,place,onDate}:{date:Date;place:Place;onDate:(d:Date)=>void}){
 const [full,setFull]=useState(false),[labels,setLabels]=useState(true),[selected,setSelected]=useState(0);const info=moonInfo(date,place),distance=A.GeoMoon(date).Length()*149597870.7;
 const quarters=useMemo(()=>{let q=A.SearchMoonQuarter(date);const result:ReturnType<typeof A.SearchMoonQuarter>[]=[];for(let i=0;i<4;i++){result.push(q);q=A.NextMoonQuarter(q)}return result},[date]);const names=['New Moon','First quarter','Full Moon','Last quarter'];const landmark=landmarks[selected];
 return <><div className="moon-layout"><section className="panel lunar-stage"><div className="section-label"><span>LUNAR SURFACE EXPLORER</span><Moon size={18}/></div><div className="moon-switches"><label><Switch checked={full} onCheckedChange={setFull} aria-label="Fully lit surface"/>Fully lit surface</label><label><Switch checked={labels} onCheckedChange={setLabels} aria-label="Landmark labels"/>Landmark labels</label></div><DeferredView name="Lunar globe"><MoonGlobe phase={info.phase} full={full} labels={labels} onSelect={setSelected}/></DeferredView><p className="footnote">Texture: <a href="https://svs.gsfc.nasa.gov/4720/" target="_blank" rel="noreferrer">NASA’s Scientific Visualization Studio / LRO ↗</a>. Surface map on a smooth sphere, with no elevation model.</p></section><div><section className="panel"><div className="section-label"><span>AT YOUR SELECTED TIME</span><Moon size={18}/></div><h2>{info.name}</h2><div className="lunar-facts"><div><strong>{Math.round(info.illumination*100)}%</strong><span>Illuminated</span></div><div><strong>{Math.round(distance).toLocaleString('en-GB')}</strong><span>km from Earth’s centre</span></div><div><strong>{info.altitude.toFixed(1)}°</strong><span>Altitude at {place.name}</span></div></div><p className="muted">{info.altitude>0?'The Moon is above your ideal horizon.':'The Moon is below your ideal horizon.'} {full?'The globe is fully lit for surface exploration.':'The globe follows the selected phase.'}</p></section><section className="panel lunar-landmarks"><div className="section-label"><span>LANDMARKS</span></div><div className="landmark-list">{landmarks.map((l,i)=><button key={l.name} className={selected===i?'active':''} onClick={()=>setSelected(i)}>{l.name}<span>{l.type}</span></button>)}</div><h3>{landmark.name}</h3><p className="muted">{Math.abs(landmark.lat).toFixed(2)}° {landmark.lat>=0?'N':'S'} · {Math.abs(landmark.lon).toFixed(2)}° {landmark.lon>=0?'E':'W'}</p><a className="text-button" href={landmark.url} target="_blank" rel="noreferrer">IAU / USGS landmark record <ArrowUpRight size={16}/></a><p className="footnote">Click a globe label to centre that landmark. Labels mark catalogue centre coordinates.</p></section></div></div><section className="panel moon-timeline"><div className="section-label"><span>THE NEXT LUNAR PHASES</span><span className="muted">Select a phase to explore it</span></div><div className="quarter-grid">{quarters.map(q=><button key={q.time.date.toISOString()} onClick={()=>onDate(q.time.date)}><Moon size={22}/><strong>{names[q.quarter]}</strong><span>{new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:place.timezone||'UTC'}).format(q.time.date)}</span><small>{timeLabel(q.time.date,place.timezone)} · {place.timezone||'UTC'}</small></button>)}</div></section><LunarEclipses date={date} place={place} onDate={onDate}/></>;
}
