"use client";
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import Image from 'next/image';
import {RotateCcw,ZoomIn,ZoomOut,ArrowLeft,ArrowRight} from 'lucide-react';
import {landmarks} from '@/lib/lunar-landmarks';
import {watchPhotoDelay} from '@/lib/photo-delay';
type GlobeActions={reset:()=>void;rotate:(delta:number)=>void;zoom:(factor:number)=>void;focus:(lat:number,lon:number)=>void;light:(phase:number,full:boolean)=>void};
export default function MoonGlobe({phase,full,labels,onSelect}:{phase:number;full:boolean;labels:boolean;onSelect:(i:number)=>void}){
 const host=useRef<HTMLDivElement>(null),labelRefs=useRef<(HTMLButtonElement|null)[]>([]),actions=useRef<GlobeActions|null>(null),latest=useRef({phase,full,labels});
 const [status,setStatus]=useState('Loading lunar surface…'),[failed,setFailed]=useState(false),[fallbackFailed,setFallbackFailed]=useState(false),[revision,setRevision]=useState(0),[slow,setSlow]=useState(false);
 const delayGeneration=useRef(0);
 const [textureSource,setTextureSource]=useState('/textures/moon-nasa.jpg');
 const retry=()=>{delayGeneration.current++;setTextureSource(`/textures/moon-nasa.jpg?nightjar-retry=${Date.now()}-${delayGeneration.current}`);setSlow(false);setStatus('Loading lunar surface…');setFailed(false);setFallbackFailed(false);setRevision(value=>value+1)};
 useEffect(()=>{let cancelled=false,disposed=false;const disposers:(()=>void)[]=[];const cleanup=()=>{if(disposed)return;disposed=true;for(const dispose of disposers.splice(0).reverse()){try{dispose()}catch{}}actions.current=null};function start(){try{if(cancelled||!host.current)return;const el=host.current;const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,100);camera.position.set(0,0,3.6);const renderer=new T.WebGLRenderer({alpha:true,antialias:true});disposers.push(()=>{renderer.dispose();if(!renderer.getContext().isContextLost())renderer.forceContextLoss();renderer.domElement.remove()});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.domElement.setAttribute('aria-label','Interactive lunar globe. Use the controls below to rotate and zoom.');renderer.domElement.setAttribute('role','img');el.appendChild(renderer.domElement);const lost=(event:Event)=>{event.preventDefault();cleanup();if(!cancelled){setFailed(true);setStatus('3D rendering stopped. The lunar surface map is shown below; retry when ready.')}};renderer.domElement.addEventListener('webglcontextlost',lost);disposers.push(()=>renderer.domElement.removeEventListener('webglcontextlost',lost));const controls=new OrbitControls(camera,renderer.domElement);disposers.push(()=>controls.dispose());controls.enablePan=false;controls.minDistance=1.6;controls.maxDistance=6;controls.enableDamping=false;const geometry=new T.SphereGeometry(1,96,64),material=new T.MeshLambertMaterial({color:0xffffff}),mesh=new T.Mesh(geometry,material);disposers.push(()=>geometry.dispose(),()=>material.dispose());mesh.rotation.y=-Math.PI/2;scene.add(mesh);const light=new T.DirectionalLight(0xffffff,3),ambient=new T.AmbientLight(0xffffff,.035);scene.add(light,ambient);
 const points=landmarks.map(l=>{const lat=l.lat*Math.PI/180,lon=l.lon*Math.PI/180;return new T.Vector3(Math.sin(lon)*Math.cos(lat),Math.sin(lat),Math.cos(lon)*Math.cos(lat))});
 function render(){if(cancelled||disposed)return;const p=latest.current;if(p.full){light.position.copy(camera.position);ambient.intensity=.5}else{const angle=p.phase*Math.PI/180;light.position.set(Math.sin(angle)*5,0,-Math.cos(angle)*5);ambient.intensity=.035}renderer.render(scene,camera);const direction=camera.position.clone().normalize();points.forEach((v,i)=>{const label=labelRefs.current[i];if(!label)return;const visible=p.labels&&v.dot(direction)>1/camera.position.length()+.02;label.hidden=!visible;if(visible){const projected=v.clone().multiplyScalar(1.01).project(camera);const x=(projected.x*.5+.5)*el.clientWidth,y=(-projected.y*.5+.5)*el.clientHeight;label.style.left=`${Math.max(4,Math.min(el.clientWidth-label.offsetWidth-4,x))}px`;label.style.top=`${Math.max(label.offsetHeight/2+4,Math.min(el.clientHeight-label.offsetHeight/2-4,y))}px`}})}
 const resize=()=>{if(!el.clientWidth||!el.clientHeight)return;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);render()};const resizeObserver=new ResizeObserver(resize);disposers.push(()=>resizeObserver.disconnect());resizeObserver.observe(el);controls.addEventListener('change',render);
 actions.current={reset:()=>{camera.position.set(0,0,3.6);camera.up.set(0,1,0);controls.target.set(0,0,0);controls.update();render()},rotate:delta=>{camera.position.applyAxisAngle(new T.Vector3(0,1,0),delta);controls.update();render()},zoom:factor=>{camera.position.setLength(Math.min(6,Math.max(1.6,camera.position.length()*factor)));controls.update();render()},focus:(lat,lon)=>{const a=lat*Math.PI/180,b=lon*Math.PI/180;camera.position.set(Math.sin(b)*Math.cos(a),Math.sin(a),Math.cos(b)*Math.cos(a)).multiplyScalar(2.6);controls.update();render()},light:()=>render()};
 new T.TextureLoader().load(textureSource,map=>{if(cancelled||disposed){map.dispose();return}disposers.push(()=>map.dispose());map.colorSpace=T.SRGBColorSpace;map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());material.map=map;material.needsUpdate=true;setSlow(false);setStatus('');render()},undefined,()=>{if(!cancelled&&!disposed){setFailed(true);setStatus('The lunar texture could not load. Retry when your connection is available.');cleanup()}});resize();
 }catch{cleanup();if(!cancelled){setFailed(true);setStatus('3D rendering is unavailable in this browser. The lunar surface map is shown below.')}}}start();return()=>{cancelled=true;cleanup()}},[revision,textureSource]);
 useEffect(()=>{if(failed||!status||!host.current)return;const token=delayGeneration.current;return watchPhotoDelay(host.current,()=>{if(token===delayGeneration.current)setSlow(true)})},[failed,status,revision]);
 useEffect(()=>{latest.current={phase,full,labels};actions.current?.light(phase,full)},[phase,full,labels]);
 return <>{slow&&Boolean(status)&&!failed&&<p className="notice" role="status">The lunar surface is taking longer to load. You can keep waiting or retry the lunar view.</p>}{failed&&!fallbackFailed&&status&&<p className="notice" role="status">{status}</p>}<div className={`moon-globe${fallbackFailed?' moon-globe-unavailable':!failed&&status?' moon-globe-loading':''}`} ref={host}>{status&&(!failed||fallbackFailed)&&<p className="globe-status" role="status">{status}</p>}{failed&&!fallbackFailed&&<Image unoptimized width={2048} height={1024} src={textureSource} alt="NASA equirectangular lunar surface map, with the near side at its centre" onError={()=>{setFallbackFailed(true);setStatus('The lunar surface map is also unavailable. Check your connection and retry the lunar view.')}}/>}{!failed&&landmarks.map((l,i)=><button hidden={!labels} ref={e=>{labelRefs.current[i]=e}} key={l.name} className="lunar-marker" onClick={()=>{onSelect(i);actions.current?.focus(l.lat,l.lon)}}>{l.name}</button>)}</div>{(failed||slow&&Boolean(status))&&<div className="lunar-retry"><button className="button" onClick={retry}><RotateCcw size={16}/>Retry lunar view</button></div>}<div className="globe-controls"><button className="button" disabled={failed||Boolean(status)} onClick={()=>actions.current?.rotate(-.25)} aria-label="Rotate Moon left"><ArrowLeft size={17}/></button><button className="button" disabled={failed||Boolean(status)} onClick={()=>actions.current?.rotate(.25)} aria-label="Rotate Moon right"><ArrowRight size={17}/></button><button className="button" disabled={failed||Boolean(status)} onClick={()=>actions.current?.zoom(.8)} aria-label="Zoom into Moon"><ZoomIn size={17}/></button><button className="button" disabled={failed||Boolean(status)} onClick={()=>actions.current?.zoom(1.25)} aria-label="Zoom out of Moon"><ZoomOut size={17}/></button><button className="button" disabled={failed||Boolean(status)} onClick={()=>actions.current?.reset()}><RotateCcw size={16}/>Near side</button></div><p className="footnote">Drag to rotate, scroll or pinch to zoom. Near-side reset places lunar north at the top. Lighting approximates the selected phase; libration, local sky orientation, terrain shadows and eclipses are not simulated.</p></>;
}
