'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Moon,RotateCcw,ZoomIn,ZoomOut,ArrowLeft,ArrowRight,ArrowUpRight} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {A,Place,moonInfo,timeLabel} from '@/lib/sky';
const landmarks=[{name:'Tycho',lat:-43.31,lon:-11.36,type:'Impact crater',url:'https://planetarynames.wr.usgs.gov/Feature/6163'},{name:'Copernicus',lat:9.62,lon:-20.08,type:'Impact crater',url:'https://planetarynames.wr.usgs.gov/Feature/1296'},{name:'Mare Tranquillitatis',lat:8.35,lon:30.83,type:'Lunar mare · Sea of Tranquility',url:'https://planetarynames.wr.usgs.gov/Feature/3691'}];
type GlobeActions={reset:()=>void;rotate:(delta:number)=>void;zoom:(factor:number)=>void;focus:(lat:number,lon:number)=>void;light:(phase:number,full:boolean)=>void};
function MoonGlobe({phase,full,labels,onSelect}:{phase:number;full:boolean;labels:boolean;onSelect:(i:number)=>void}){
 const host=useRef<HTMLDivElement>(null),labelRefs=useRef<(HTMLButtonElement|null)[]>([]),actions=useRef<GlobeActions|null>(null),latest=useRef({phase,full,labels});latest.current={phase,full,labels};
 const [status,setStatus]=useState('Loading lunar surface…'),[failed,setFailed]=useState(false);
 useEffect(()=>{let cancelled=false,cleanup=()=>{};async function start(){try{const [T,{OrbitControls}]=await Promise.all([import('three'),import('three/addons/controls/OrbitControls.js')]);if(cancelled||!host.current)return;const el=host.current;const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.1,100);camera.position.set(0,0,3.6);const renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.domElement.setAttribute('aria-label','Interactive lunar globe. Use the controls below to rotate and zoom.');renderer.domElement.setAttribute('role','img');el.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.minDistance=1.6;controls.maxDistance=6;controls.enableDamping=false;const geometry=new T.SphereGeometry(1,96,64),material=new T.MeshLambertMaterial({color:0xffffff}),mesh=new T.Mesh(geometry,material);mesh.rotation.y=-Math.PI/2;scene.add(mesh);const light=new T.DirectionalLight(0xffffff,3),ambient=new T.AmbientLight(0xffffff,.035);scene.add(light,ambient);let texture:import('three').Texture|undefined;
 const points=landmarks.map(l=>{const lat=l.lat*Math.PI/180,lon=l.lon*Math.PI/180;return new T.Vector3(Math.sin(lon)*Math.cos(lat),Math.sin(lat),Math.cos(lon)*Math.cos(lat))});
 function render(){if(cancelled)return;const p=latest.current;if(p.full){light.position.copy(camera.position);ambient.intensity=.5}else{const angle=p.phase*Math.PI/180;light.position.set(Math.sin(angle)*5,0,-Math.cos(angle)*5);ambient.intensity=.035}renderer.render(scene,camera);const direction=camera.position.clone().normalize();points.forEach((v,i)=>{const label=labelRefs.current[i];if(!label)return;const visible=p.labels&&v.dot(direction)>1/camera.position.length()+.02;label.hidden=!visible;if(visible){const projected=v.clone().multiplyScalar(1.01).project(camera);label.style.left=`${(projected.x*.5+.5)*el.clientWidth}px`;label.style.top=`${(-projected.y*.5+.5)*el.clientHeight}px`}})}
 const resize=()=>{if(!el.clientWidth)return;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);render()};const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(el);controls.addEventListener('change',render);
 actions.current={reset:()=>{camera.position.set(0,0,3.6);camera.up.set(0,1,0);controls.target.set(0,0,0);controls.update();render()},rotate:delta=>{camera.position.applyAxisAngle(new T.Vector3(0,1,0),delta);controls.update();render()},zoom:factor=>{camera.position.setLength(Math.min(6,Math.max(1.6,camera.position.length()*factor)));controls.update();render()},focus:(lat,lon)=>{const a=lat*Math.PI/180,b=lon*Math.PI/180;camera.position.set(Math.sin(b)*Math.cos(a),Math.sin(a),Math.cos(b)*Math.cos(a)).multiplyScalar(2.6);controls.update();render()},light:()=>render()};
 cleanup=()=>{resizeObserver.disconnect();controls.dispose();texture?.dispose();material.dispose();geometry.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();actions.current=null};
 new T.TextureLoader().load('/textures/moon-nasa.jpg',map=>{if(cancelled){map.dispose();return}texture=map;map.colorSpace=T.SRGBColorSpace;map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());material.map=map;material.needsUpdate=true;setStatus('');render()},undefined,()=>{if(!cancelled){setFailed(true);setStatus('The lunar texture could not load.');cleanup()}});resize();
 }catch{if(!cancelled){setFailed(true);setStatus('3D rendering is unavailable in this browser. The lunar surface map is shown below.')}}}start();return()=>{cancelled=true;cleanup()}},[]);
 useEffect(()=>{actions.current?.light(phase,full)},[phase,full,labels]);
 return <><div className="moon-globe" ref={host}>{status&&<p className="globe-status" role="status">{status}</p>}{failed&&<img src="/textures/moon-nasa.jpg" alt="NASA equirectangular lunar surface map, with the near side at its centre"/>}{!failed&&landmarks.map((l,i)=><button hidden={!labels} ref={e=>{labelRefs.current[i]=e}} key={l.name} className="lunar-marker" onClick={()=>{onSelect(i);actions.current?.focus(l.lat,l.lon)}}>{l.name}</button>)}</div><div className="globe-controls"><button className="button" disabled={failed} onClick={()=>actions.current?.rotate(-.25)} aria-label="Rotate Moon left"><ArrowLeft size={17}/></button><button className="button" disabled={failed} onClick={()=>actions.current?.rotate(.25)} aria-label="Rotate Moon right"><ArrowRight size={17}/></button><button className="button" disabled={failed} onClick={()=>actions.current?.zoom(.8)} aria-label="Zoom into Moon"><ZoomIn size={17}/></button><button className="button" disabled={failed} onClick={()=>actions.current?.zoom(1.25)} aria-label="Zoom out of Moon"><ZoomOut size={17}/></button><button className="button" disabled={failed} onClick={()=>actions.current?.reset()}><RotateCcw size={16}/>Near side</button></div><p className="footnote">Drag to rotate, scroll or pinch to zoom. Near-side reset places lunar north at the top. Lighting approximates the selected phase; libration, local sky orientation, terrain shadows and eclipses are not simulated.</p></>;
}
export default function MoonExplorer({date,place,onDate}:{date:Date;place:Place;onDate:(d:Date)=>void}){
 const [full,setFull]=useState(false),[labels,setLabels]=useState(true),[selected,setSelected]=useState(0);const info=moonInfo(date,place),distance=A.GeoMoon(date).Length()*149597870.7;
 const quarters=useMemo(()=>{let q=A.SearchMoonQuarter(date);return Array.from({length:4},()=>{const item=q;q=A.NextMoonQuarter(q);return item})},[date]);const names=['New Moon','First quarter','Full Moon','Last quarter'];const landmark=landmarks[selected];
 return <><div className="moon-layout"><section className="panel lunar-stage"><div className="section-label"><span>LUNAR SURFACE EXPLORER</span><Moon size={18}/></div><div className="moon-switches"><label><Switch checked={full} onCheckedChange={setFull} aria-label="Fully lit surface"/>Fully lit surface</label><label><Switch checked={labels} onCheckedChange={setLabels} aria-label="Landmark labels"/>Landmark labels</label></div><MoonGlobe phase={info.phase} full={full} labels={labels} onSelect={setSelected}/><p className="footnote">Texture: <a href="https://svs.gsfc.nasa.gov/4720/" target="_blank" rel="noreferrer">NASA’s Scientific Visualization Studio / LRO ↗</a>. Surface map on a smooth sphere, with no elevation model.</p></section><div><section className="panel"><div className="section-label"><span>AT YOUR SELECTED TIME</span><Moon size={18}/></div><h2>{info.name}</h2><div className="lunar-facts"><div><strong>{Math.round(info.illumination*100)}%</strong><span>Illuminated</span></div><div><strong>{Math.round(distance).toLocaleString('en-GB')}</strong><span>km from Earth’s centre</span></div><div><strong>{info.altitude.toFixed(1)}°</strong><span>Altitude at {place.name}</span></div></div><p className="muted">{info.altitude>0?'The Moon is above your ideal horizon.':'The Moon is below your ideal horizon.'} {full?'The globe is fully lit for surface exploration.':'The globe follows the selected phase.'}</p></section><section className="panel lunar-landmarks"><div className="section-label"><span>LANDMARKS</span></div><div className="landmark-list">{landmarks.map((l,i)=><button key={l.name} className={selected===i?'active':''} onClick={()=>setSelected(i)}>{l.name}<span>{l.type}</span></button>)}</div><h3>{landmark.name}</h3><p className="muted">{Math.abs(landmark.lat).toFixed(2)}° {landmark.lat>=0?'N':'S'} · {Math.abs(landmark.lon).toFixed(2)}° {landmark.lon>=0?'E':'W'}</p><a className="text-button" href={landmark.url} target="_blank" rel="noreferrer">IAU / USGS landmark record <ArrowUpRight size={16}/></a><p className="footnote">Click a globe label to centre that landmark. Labels mark catalogue centre coordinates.</p></section></div></div><section className="panel moon-timeline"><div className="section-label"><span>THE NEXT LUNAR PHASES</span><span className="muted">Select a phase to explore it</span></div><div className="quarter-grid">{quarters.map(q=><button key={q.time.date.toISOString()} onClick={()=>onDate(q.time.date)}><Moon size={22}/><strong>{names[q.quarter]}</strong><span>{new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:place.timezone||'UTC'}).format(q.time.date)}</span><small>{timeLabel(q.time.date,place.timezone)} · {place.timezone||'UTC'}</small></button>)}</div></section></>;
}
