'use client';
import {useMemo} from 'react';
import {Telescope} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell,TableCaption} from '@/components/ui/table';
import {A,bodyPosition,Place,timeLabel} from '@/lib/sky';
export default function PlanetVisibility({date,place,onDate}:{date:Date;place:Place;onDate:(date:Date)=>void}){
 const start=Math.floor(+date/3600000)*3600000,tz=place.timezone||'UTC';
 const data=useMemo(()=>{const hours=Array.from({length:12},(_,i)=>{const time=new Date(start+i*3600000);return{time,sun:bodyPosition(A.Body.Sun,time,place).altitude}});return{hours,rows:[A.Body.Moon,A.Body.Venus,A.Body.Mars,A.Body.Jupiter,A.Body.Saturn].map(body=>{const positions=hours.map(h=>({...h,...bodyPosition(body,h.time,place)}));const best=positions.filter(p=>p.sun<=-6&&p.altitude>0).reduce<(typeof positions)[number]|null>((a,b)=>!a||b.altitude>a.altitude?b:a,null);return{body,positions,best}})}},[start,place]);
 const stamp=(d:Date)=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:tz}).format(d);
 return <section className="panel planet-visibility"><div className="section-label"><span>WHEN TO LOOK</span><Telescope size={18}/></div><p className="muted">Hourly altitude samples for {place.name}, starting at {stamp(new Date(start))} ({tz}). Select a cell to update the sky atlas.</p><Table className="visibility-table"><TableCaption>Altitude above an ideal horizon: negative values are below it. Highlighted cells are at least 30° high; they do not guarantee visibility. Weather, terrain, glare and brightness are not included.</TableCaption><TableHeader><TableRow><TableHead scope="col">Object</TableHead>{data.hours.map(h=><TableHead scope="col" key={+h.time}><span>{timeLabel(h.time,tz)}</span><small>{h.time.toISOString().slice(11,16)} UTC</small><small>{h.sun<=-18?'Dark':h.sun<=-6?'Twilight':'Day / civil'}</small></TableHead>)}</TableRow></TableHeader><TableBody>{data.rows.map(row=><TableRow key={row.body}><TableHead scope="row">{row.body}</TableHead>{row.positions.map(p=><TableCell key={+p.time}><button className={p.altitude>=30?'altitude high':p.altitude>0?'altitude low':'altitude below'} onClick={()=>onDate(p.time)} aria-label={`View ${row.body} at ${stamp(p.time)}, altitude ${p.altitude.toFixed(1)} degrees`} title={`${p.altitude.toFixed(1)}° altitude · ${p.azimuth.toFixed(1)}° azimuth`}><span>{p.altitude.toFixed(0)}°</span><small>{p.altitude>0?'Above':'Below'}</small></button></TableCell>)}</TableRow>)}</TableBody></Table><div className="planet-best-grid">{data.rows.map(row=><div key={row.body}><strong>{row.body}</strong>{row.best?<button className="text-button" onClick={()=>onDate(row.best!.time)}>{stamp(row.best.time)} · {Math.round(row.best.altitude)}°</button>:<span>No sample above the horizon after civil twilight</span>}</div>)}</div><p className="footnote">The shortcuts choose each object’s highest hourly sample with the Sun at least 6° below the horizon, within this 12-hour window. These are sampled opportunities, not exact transit times. Civil twilight is grouped with daylight; “Dark” means the Sun is at least 18° below the horizon.</p></section>;
}
