import {normalizeDiary,type Observation} from './observing-diary';
import {diaryLocalTime} from './diary-time';
const labels={'seen':'Seen','not-seen':'Not seen','imaged':'Imaged'};
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
function sorted(entries:Observation[]){return normalizeDiary(entries).sort((a,b)=>b.observedAt.localeCompare(a.observedAt)||a.id.localeCompare(b.id))}
// Quote all cells, and prefix text that spreadsheets may interpret as a formula.
function cell(value:string){const safe=/^[\s\uFEFF]*[=+\-@]/.test(value)||/^[\t\r\n]/.test(value)?`'${value}`:value;return `"${safe.replace(/"/g,'""')}"`}
export function diaryCSV(entries:Observation[]):string{
 const header=['Entry ID','Object','Observed UTC','Site local time','Time zone','Site','Latitude','Longitude','Bortle rating','Result','Equipment','Notes'];
 const rows=sorted(entries).map(entry=>[cell(entry.id),cell(entry.target),cell(entry.observedAt),cell(diaryLocalTime(entry)),cell(entry.place.timezone||'UTC'),cell(entry.place.name),String(entry.place.latitude),String(entry.place.longitude),String(entry.place.bortle??''),cell(labels[entry.outcome]),cell(entry.equipment),cell(entry.notes)].join(','));
 return '\uFEFF'+[header.map(cell).join(','),...rows].join('\r\n')+'\r\n';
}
export function diaryReport(entries:Observation[]):string{
 const rows=sorted(entries),articles=rows.map(entry=>`<article><div class="entry-heading"><h2>${escape(entry.target)}</h2><span>${labels[entry.outcome]}</span></div><p class="date">${escape(diaryLocalTime(entry))} · ${escape(entry.place.timezone||'UTC')}</p><dl><div><dt>UTC INSTANT</dt><dd>${escape(entry.observedAt)}</dd></div><div><dt>OBSERVING SITE</dt><dd>${escape(entry.place.name)} · ${entry.place.latitude.toFixed(5)}°, ${entry.place.longitude.toFixed(5)}°${entry.place.bortle?` · Bortle ${entry.place.bortle}`:''}</dd></div><div><dt>EQUIPMENT</dt><dd>${escape(entry.equipment||'Not recorded')}</dd></div></dl><h3>Observation notes</h3><p class="notes">${escape(entry.notes||'No notes recorded.')}</p></article>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Nightjar observing diary</title><style>
*{box-sizing:border-box}body{margin:0;background:#edf0ea;color:#1d2a1e;font:16px/1.6 system-ui,sans-serif}main{max-width:850px;margin:24px auto;background:#fff;padding:36px;border-radius:12px}.brand{color:#526947;font-size:17px}h1{font-size:32px;line-height:1.2;margin:12px 0}h2{font-size:22px;margin:0}h3{font-size:14px;margin:20px 0 8px}p{margin:8px 0}.hint,.date,footer{font-size:13px;color:#52664c}button{font:inherit;background:#263b24;color:white;border:0;border-radius:7px;padding:12px 18px;min-height:44px;cursor:pointer}button:focus-visible{outline:2px solid #466036;outline-offset:4px}article{border:1px solid #bcc7b7;border-radius:8px;padding:22px;margin:20px 0;break-inside:avoid}.entry-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.entry-heading span{border:1px solid #bcc7b7;border-radius:20px;font-size:13px;padding:4px 12px}dl{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:20px 0}dt{font-size:11px;color:#52664c}dd{margin:6px 0 0;overflow-wrap:anywhere;font-size:14px}.notes{white-space:pre-wrap;overflow-wrap:anywhere}footer{border-top:1px solid #bcc7b7;padding-top:18px;margin-top:28px}@media(max-width:600px){main{padding:22px 16px;margin:0;border-radius:0}dl{grid-template-columns:1fr}article{padding:16px}}@media print{@page{margin:16mm}body{background:white;font-size:12pt}main{max-width:none;margin:0;padding:0;border-radius:0}.print-controls{display:none}h1{font-size:24pt}article{padding:14px}dl{grid-template-columns:1fr 1fr}}
</style></head><body><main><div class="brand">nightjar. · OBSERVING DIARY</div><h1>Your nights, recorded.</h1><p>${rows.length} saved observation${rows.length===1?'':'s'} · newest first</p><div class="print-controls"><button type="button" id="print-diary">Print or save as PDF</button><p class="hint">This report opens offline and contains the saved entries selected when you downloaded it.</p></div>${articles||'<p>No saved observations in this report.</p>'}<footer>These are your recorded observations, with their original sites and times. This report is a snapshot; it does not update forecasts or sky positions. Changes to this file do not change Nightjar. Use a Nightjar backup to restore data on another device.</footer></main><script>document.getElementById('print-diary').addEventListener('click',function(){window.print()})</script></body></html>`;
}
