import {A,bodyPosition,moonInfo,skyTargetLimit,type Place} from './sky';
import {validPlace} from './planner-state';
import {type Equipment,validEquipment} from './photography';

type Target={name:string;altitude:number;azimuth:number};
type Plan={date:Date;place:Place;targets:Target[];notes:Record<string,string>;equipment:Equipment[];equipmentUnavailable?:boolean;equipmentOmitted?:number;notesUnavailable?:boolean;notesUnsaved?:boolean;notesHeading?:'Personal notes'|'Catalogue reference';catalogueNotice?:string};
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const direction=(azimuth:number)=>['N','NE','E','SE','S','SW','W','NW'][Math.round(azimuth/45)%8];
export function notesCoverageNotice(unavailable:boolean,unsaved:boolean){
 return [unavailable?'Personal notes could not be read from browser storage. This checklist uses notes currently shown in Nightjar, which may be from an earlier successful read.':'',unsaved?'This checklist includes unsaved note edits from the current Sky atlas view. They may not be stored on this browser.':''].filter(Boolean).join(' ');
}
export function printableObservingPlan(input:Plan):string{
 const {date,place,targets,notes,equipment}=input,omitted=input.equipmentOmitted??0;
 if(!Number.isSafeInteger(omitted)||omitted<0||!Number.isSafeInteger(equipment.length+omitted)||input.equipmentUnavailable&&omitted>0)throw Error('The equipment coverage is invalid.');
 if(!Number.isFinite(+date)||!validPlace(place)||targets.length>skyTargetLimit+109||!targets.every(target=>typeof target.name==='string'&&target.name.length<=100&&Number.isFinite(target.altitude)&&Math.abs(target.altitude)<=90&&Number.isFinite(target.azimuth)&&target.azimuth>=0&&target.azimuth<=360)||equipment.length>100||!equipment.every(validEquipment))throw Error('The observing plan contains invalid data.');
 const zone=place.timezone||'UTC',notesNotice=notesCoverageNotice(Boolean(input.notesUnavailable),Boolean(input.notesUnsaved));
 const local=new Intl.DateTimeFormat('en-GB',{timeZone:zone,weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',timeZoneName:'shortOffset'}).format(date);
 const moon=moonInfo(date,place),sun=bodyPosition(A.Body.Sun,date,place).altitude;
 const night=sun<-18?'Astronomical darkness':sun<=-6?'Twilight':'Daylight / civil twilight';
 const sorted=[...targets].sort((a,b)=>b.altitude-a.altitude);
 const articles=sorted.map((target,index)=>{
  const note=typeof notes[target.name]==='string'?notes[target.name].slice(0,2000):'';
  return `<article><div class="target-heading"><input type="checkbox" id="target-${index}"><label for="target-${index}">${escape(target.name)}</label><span>${target.altitude>0?'Above horizon':'Below horizon'}</span></div><p class="position">Altitude ${target.altitude.toFixed(1)}° · Azimuth ${target.azimuth.toFixed(1)}° (${direction(target.azimuth)})</p><h3>${input.notesHeading==='Catalogue reference'?'Catalogue reference':'Personal notes'}</h3>${note?`<p class="notes">${escape(note)}</p>`:'<div class="blank-notes" aria-label="Space for observing notes"></div>'}</article>`;
 }).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Nightjar observing plan — ${escape(place.name)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#eef1ed;color:#172218;font:16px/1.6 system-ui,sans-serif}main{max-width:850px;margin:24px auto;background:white;padding:36px;border-radius:12px}h1{font-size:32px;line-height:1.2;margin:12px 0;overflow-wrap:anywhere}h2{font-size:21px;margin:28px 0 14px}h3{font-size:13px;margin:14px 0 5px;font-weight:600}p{margin:7px 0}.brand{font-size:17px;letter-spacing:-.4px;color:#466036}.meta{display:grid;grid-template-columns:1fr 1fr;gap:14px;border:1px solid #bcc7b7;border-radius:8px;padding:16px;margin:20px 0}.meta strong{display:block;font-size:12px;color:#52664c}.meta span{display:block;overflow-wrap:anywhere}article{border:1px solid #bcc7b7;border-radius:8px;padding:18px;margin:14px 0;break-inside:avoid}.target-heading{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.target-heading label{font-size:19px;font-weight:600;max-width:100%;overflow-wrap:anywhere}.target-heading span{margin-left:auto;font-size:12px;color:#52664c}.target-heading input{width:22px;height:22px;accent-color:#466036}.position{font-size:13px;color:#52664c}.notes{white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px}.blank-notes{height:55px;border-bottom:1px dashed #899b81}button{font:inherit;background:#263b24;color:white;border:0;border-radius:7px;padding:12px 18px;min-height:44px;cursor:pointer}button:focus-visible,input:focus-visible{outline:2px solid #466036;outline-offset:4px}.hint,footer{font-size:13px;color:#52664c}li{overflow-wrap:anywhere;margin:6px 0}footer{border-top:1px solid #bcc7b7;padding-top:18px;margin-top:28px}@media(max-width:600px){main{padding:22px 16px;margin:0;border-radius:0}.meta{grid-template-columns:1fr}.target-heading span{margin-left:0;width:100%}}@media print{@page{margin:16mm}body{background:white;font-size:12pt}main{max-width:none;margin:0;padding:0;border-radius:0}.print-controls{display:none}h1{font-size:24pt}h2{break-after:avoid}article{padding:12px}.meta{grid-template-columns:1fr 1fr}input{appearance:none;border:1px solid #172218;border-radius:2px}input:checked::after{content:'✓';display:block;text-align:center;line-height:20px}a{color:inherit}}
</style></head><body><main><div class="brand">nightjar. · OBSERVING PLAN</div><h1>${escape(place.name)}</h1><div class="print-controls"><button type="button" id="print-plan">Print or save as PDF</button><p class="hint">This file opens offline. Tick targets as you observe; tick marks last while this file is open. It contains your site details and ${input.notesHeading==='Catalogue reference'?'catalogue references':'personal notes'}.</p></div><div class="meta"><div><strong>SITE COORDINATES</strong><span>${place.latitude.toFixed(4)}°, ${place.longitude.toFixed(4)}°${place.bortle?` · Bortle ${place.bortle}`:''}</span></div><div><strong>TIME AT SITE</strong><span>${escape(local)} · ${escape(zone)}</span></div><div><strong>UTC INSTANT</strong><span>${date.toISOString().replace('T',' ').replace('Z',' UTC')}</span></div><div><strong>SKY AT SELECTED TIME</strong><span>${night} · Sun ${sun.toFixed(1)}° altitude</span></div></div><p>Moon: ${escape(moon.name)} · ${Math.round(moon.illumination*100)}% illuminated · ${moon.altitude>0?'above':'below'} horizon (${moon.altitude.toFixed(1)}°).</p>${notesNotice?`<p class="hint notes-coverage">${escape(notesNotice)}</p>`:''}<h2>Target checklist · ${sorted.length}</h2><p class="hint">Highest altitude first. Positions are a snapshot at the time and site above.</p>${articles||'<p>No saved catalogue targets in this plan.</p>'}<h2>Saved equipment</h2>${omitted>0?`<p class="hint">Showing the first ${equipment.length} of ${equipment.length+omitted} saved setups. ${omitted} additional ${omitted===1?'setup is':'setups are'} not included in this checklist.</p>`:''}${input.equipmentUnavailable?'<p>Equipment could not be read from browser storage.</p>':equipment.length?`<ul>${equipment.map(setup=>`<li><strong>${escape(setup.name)}</strong> · ${setup.focal} mm · ${setup.width} × ${setup.height} mm sensor · ${setup.pixel} µm pixels</li>`).join('')}</ul>`:'<p>No equipment saved on this device.</p>'}<footer>${input.catalogueNotice?`${escape(input.catalogueNotice.slice(0,1000))} `:''}Star positions are approximate; planets and the Moon are calculated. Above the ideal horizon does not guarantee visibility: daylight, weather, terrain and obstructions matter. Live weather is not included. Check conditions before heading out. This file is a checklist, not a data backup.</footer></main><script>document.getElementById('print-plan').addEventListener('click',function(){window.print()})</script></body></html>`;
}
